echobind/bisonapp

- README.md
> feat: initial release

- template/README.md
> chore(docs): update readme for clarity

- template/_package.json
- template/_templates/cells/new/new.ejs
This adds a generator for cells (concept taken directly from RedwoodJS).
Fixes #7
> feat(generators): adds cell generator

- package.json
This worked locally but caused an error when using the published version. This is why we test prod deploys before announcing them! 😂
> fix(cli): include logo and postinstall text files

- README.md
- postInstallText.js
- template/.github/workflows/main.js.yml
> fix(cli): remove outdated Vercel instructions. Update README.

- README.md
- postInstallText.js
- template/README.md
- template/_package.json
This streamlines initial setup a bit by running the initial migrate command followed by `prisma generate`
> feat(db): adds db:setup script

- README.md
Suggested README copy changes.
> Updating some copy in the README

- README.md
- cli.js
- index.js
- template/_.env.test.ejs
- template/prisma/_.env.ejs
- template/tests/jest.setup.js.ejs
This prompts the user for database info rather than us assuming.
- update prisma .env
- update jest.setup
- update .env.local
- update .env.test
Fixes #36 
~## Merge #38 first~
> feat(cli): ask for database information

- template/lib/prisma.ts
- template/prisma/seeds.js
- Replace db.disconnect() by db.$disconnect()
n/a
n/a
Fixes #41
> chore: replace db.disconnect() by db.$disconnect()

- README.md
> docs: Fixed typo in Getting Started section

- template/package.json.ejs
This was outputting blank lines in the package.json, which we don't want. this PR fixes it.
- Clean up `package.json` template
n/a
> fix: remove whitespace from package.json

- template/package.json.ejs
It is already included via ts-node-dev.
- removes ts-node from package.json template.
n/a
> chore: remove extra ts-node dependency

- package.json
- packages/create-bison-app/template/graphql/modules/user.ts.ejs
- Adds necessary nexus pieces to match `profile` input
> fix: update inputObjectType for signup

- packages/create-bison-app/template/package.json.ejs
- packages/create-bison-app/template/tests/utils.tsx
- Upgrade to the latest version of next which contains no breaking changes
Fixes #145
> chore: upgrade next

- packages/create-bison-app/postInstallText.ejs
- packages/create-bison-app/scripts/createDevAppAndStartServer.js
- packages/create-bison-app/template/README.md.ejs
- packages/create-bison-app/template/package.json.ejs
- packages/create-bison-app/template/scripts/buildProd.ts
Dev Setup Scripts:
- Add build:types (prisma, nexus, codgen)
- update buildProd script with new command
- add setup:dev script for generating types and running db:setup
Fixes #164
> feat(enhancement): Dev Setup Scripts

- packages/create-bison-app/template/_templates/test/factory/factory.ejs
- packages/create-bison-app/template/tests/factories/user.ts
- packages/create-bison-app/template/tests/requests/user/signup.test.ts
fix: Removes generated id from factory in favor of DB
Fixes #144
> fix: Removes generated id from factory in favor of DB

- packages/create-bison-app/template/_templates/graphql/new/graphql.ejs
- packages/create-bison-app/template/graphql/modules/user.ts.ejs
feat(enhancement): Upgrade to `queryField` and `mutationField`:
- Updates user.ts.ejs example
- Updates graphql.ejs template
Fixes #175
> feat(enhancement): Upgrade to queryField and mutationField:

- docs/devWorkflow.md
- docs/nexus-examples.md
- docs/request-spec-examples.md
- Updates Nexus TODO with example doc
https://github.com/echobind/bisonapp/blob/17a8c5ff469bc59a9edbb96cc238fff7fd906bf2/docs/nexus-examples.md
- Request Spec Example Docs: 
https://github.com/echobind/bisonapp/blob/d3613487b6f9baaf7c04a47ea945c2c775f79b1b/docs/request-spec-examples.md
closes #186
> Nexus Example Doc

- packages/create-bison-app/template/_.gitignore
This fixes a bug in CI where the folder was missing.
Adds `.gitkeep` for cypress/videos cypress/screenshots & cypress/logs
> fix: Cypress keep

- packages/create-bison-app/template/README.md.ejs
- Fixes URL to CI status badge in template readme
> docs: fix status badge url

- packages/create-bison-app/tasks/copyFiles.js
- packages/create-bison-app/template/__mocks__/fileMock.d.ts
- packages/create-bison-app/template/jest.config.js
- Added moduleMapper in the jest config to support images
- Added a mock file for svgs
Fixes #240
> test: add support for svg

- packages/create-bison-app/template/.github/PULL_REQUEST_TEMPLATE.md
Updates pull request template to migrate the ticket id format and link from Clubhouse to Shortcut: https://help.shortcut.com/hc/en-us/articles/207540323-Using-Branches-and-Pull-Requests-with-the-Shortcut-VCS-Integrations#work-with-pr
> chore: update PR template to use new format for story number and link for Shortcut
