template/_templates/component/new/new.ejs
This fixes an issue where the generators tried to create a directory like `components//MyComponent.tsx`.
=> fix(generators): fix bug in component path

template/_package.json
We can keep this more generic by using `next dev` instead. This still reads env vars.
=> feat(scripts): uses next dev instead of vercel dev

template/_.env.local
Without this the server was blowing up after generating.
=> fix(env): Adds a default value for APP_SECRET

template/_.env.test
A default `APP_SECRET` was not added to .env.test and was causing tests to fail in the generated app.
- Adds default value for `APP_SECRET` to .env.test
Prevents the following:
Fixes #20
=> fix(env): add default APP_SECRET value to test env

index.js
This is required to run tests without errors. Prior to this, users would need to run it manually.
- Generates the Nexus types during initial setup
Fixes #21
=> fix(types): run nexus build during setup.

index.js
This prevents an error on installation. We need to generate Prisma types before we try and generate anything with Nexus.
- Adds "Generate Prisma client" step
Fixes #24
=> fix(cli): generate prisma client before nexus types

.github/PULL_REQUEST_TEMPLATE.md, LICENSE, README.md, index.js, postInstallText.js, template/README.md, template/_.env.local, template/_.env.test, template/_package.json, template/tests/jest.setup.js
Schema value reference in jest setup script is null/undefined. This results in the teardown script failing to drop the temporary test schema.
=> fix: schema value referenced is null resulting in the schema not being dropped during jest teardown

.github/workflows/release.yml, package.json
This updates GH actions workflow and semantic release to use `main and `next` branches
- Updates release GH Actions workflow
- Updates semantic release branch config
n/a
Fixes #32
=> chore: run GitHub Actions on main and next

package.json
This was an oversight when moving to ejs...
- Make sure it's included.
n/a
=> fix: include postInstallText in package.

template/utils/setErrors.ts
Upgrade of react-hook-form created a type error deploying to Vercel
removed curly braces and added typeof to setError.ts
(prefer animated gif)
Fixes #xxx
=> fix: setError errorOption

README.md
Updated the README and linked to Blitz and Redwood in the sections where they are referred to.
=> docs: update README with links to Blitz / Redwood

template/package.json.ejs
This PR upgrades the `nexus-plugin-prisma` package.
- Version 0.18.0 of this package introduces various [BREAKING CHANGES](https://github.com/graphql-nexus/nexus-plugin-prisma/releases/tag/0.18.0). These should be reviewed by the development team prior to upgrading Bison.
=> chore: upgrade nexus-plugin-prisma package

template/components/Nav.tsx
Thanks to @agustif for the heads up on this one!
- Menu button should use the `as` prop with Button
Before:
After:
Fixes #58
=> fix: use as prop on MenuButton to fix types

template/lib/prisma.ts
This moves to the non-deprecated [`prisma.$connect`](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/connection-management#connect) method. Like mentioned in #57, disconnect is already taken care of so this should be good to go in the next release.
- prisma.connect -> prisma.$connect
n/a
Fixes #57
=> fix: remove deprecated prisma.connect from template

template/_templates/graphql/new/graphql.ejs
Nexus will error out if a previous `queryType` is already defined. We're planning to include a "global" that sets this - so ensuring that generated modules just extend Query will ensure this error does not happen for a dev.
- Replaces `queryType` in our generated template with `extendType`
=> fix: replace queryType with extendType

docs/devWorkflow.md
[rendered](https://github.com/echobind/bisonapp/blob/chore/update-dev-workflow-doc/docs/devWorkflow.md)
This PR extends the dev workflow doc to include 1) examples for the API and 2) add the Prisma schema step.
- Adds example utilizing the real-world example of `Organization` type
- Includes Prisma schema step
=> chore: extend the dev workflow doc with examples

package.json
In the last PR, the `utils` folder wasn't added to the final package output, so once installed it failed to locate the file.
- add utils to files property of package.json
n/a
Fixes #70
=> fix(npm): include utils folder in final package

template/package.json.ejs
This was missed in #68. Additionally, we needed a few additional build scripts to ensure a proper production build.
- add nexus, next, and prisma build scripts to ensure a proper production build.
n/a
Fixes #72
=> fix: remove nexus build from build script

template/scripts/dropDatabase.ts
There was a linting error in the `dropDatabase` script that was causing codegen to fail.
- disable eslint in the script
Before:
After:
Fixes #78
=> fix:  lint error in dropDatabase broke codegen

index.js, template/package.json.ejs
This PR fixes an issue generating the prisma client. It also upgrades prisma and the nexus plugin for a few related fixes.
**Nexus Plugin updates (https://github.com/graphql-nexus/nexus-plugin-prisma/releases/tag/0.21.0):** 
---
**Prisma updates (https://github.com/prisma/prisma/releases):**
Even though I can't fully reproduce it, it should also fix the issue discovered in #76.
- Upgrade prisma to 2.8.1
- Upgrade Nexus Prisma Plugin to 0.21
n/a
Fixes #76
=> fix: fix prisma gen folder path, upgrade prisma client & nexus plugin

cypress/integration/createBisonAppWithDefaults.test.js, template/graphql/schema.ts
There was a problem with the configuration for nexus schema typegen. Sometimes it would return the correct directory and others it would return `/`. This uses `path.cwd` for more consistency.
- use path.cwd for typegen paths
- add e2e test to make sure that playground loads
Before:
After:
Fixes #84
=> fix: use path.cwd to determine paths for typegen

template/api.graphql, template/graphql/context.ts, template/tests/helpers.ts, template/tests/requests/user/login.test.ts, template/tests/requests/user/me.test.ts, template/tests/requests/user/signup.test.ts
This fixes a few issues from #66 that were missed and caused tests in a newly generated app to fail.
- regenerate `api.graphql` file
- adds `prisma` alias to context
- relaxes regex around test schema parsing to avoid database truncation errors
- updates snapshots to reflect error message and cache control updates
Fixes #92
=> fix(tests): ensure the generated tests pass

.github/workflows/release.yml, .github/workflows/tests.yml, package.json, template/.github/workflows/main.js.yml.ejs
Prior to this, Node 14 was required due to the use of the optional chaining operator. This removes it and ensures tests run on multiple Node versions.
- Remove use of optional chaining
- Split Github Actions into 2 workflows: test & release
- Add test matrix to ensure different node versions work
Fixes #91
=> fix(cli): fix create-bison-app on Node versions < 14

cli.js, index.js, template/.github/workflows/main.js.yml.ejs, template/package.json.ejs, template/scripts/buildProd.ts, test/tasks/copyFiles.test.js
This ensures that builds are migrated properly for branches we care about (the staging and prod branches)
In order to properly do this, we add a bison config to package.json. That stores:
* The version used to init the project
* the staging branch
* the production branch
Once we move to Lerna and have a separate Bison package, we wont need the version. But until that time it will be really helpful in helping users upgrade to the latest improvements.
- add `buildProd` script which handles migrate & build
- ask users what branches to use for staging/production. This is to drive migrations for staging/prod databases, but also paves the way in the future to help handle branch merging or other branch based configurations.
- forces `build:nexus` to use `NODE_ENV=development`. This is a huge …
=> feat: add migrate on deploy and bison config to package.json

template/scripts/yarnWithEnv.ts
If the child process failed, we previously ignored it.
- ensure that we exit the process if the child process exits.
(prefer animated gif)
Fixes #98
=> fix: ensure yarnWithEnv script properly exits

README.md, docs/ci.md, packages/create-bison-app/logo.js, packages/create-bison-app/package.json, packages/create-bison-app/template/.github/workflows/main.js.yml.ejs
JAMstack -> Jamstack
In [December of last year](https://github.com/jamstack/jamstack.org/commit/41c0b767694c1f8c7e3fabcb1e0d770b154c00d7) Netlify made a slight modification to the Jamstack brand that they have cultivated and removed the all uppercase JAM.
Here's Chris Coyier's take on it: [JAMstack vs. Jamstack](https://css-tricks.com/jamstack-vs-jamstack/). For me, the reasoning I would switch this Bison repo specifically doesn't really have anything to do with the argument about the acronym.
It's more so that I just think it's been long enough to definitively say it's not gonna change back. But if you want to keep it the way it is and go old school then more power to you! And I'd also change Full Stack to Fullstack, just cause Fullstack Jamstack looks so much cleaner to me. But that's …
=> docs: Change all uses of JAMstack to Jamstack

packages/create-bison-app/template/prisma/_.env.ejs, packages/create-bison-app/test/tasks/copyFiles.test.js
Description of PR that completes issue here...
When I ran `npx create-bison-app MyApp` on my local machine, I initialized the database with:
username: postgres
password: docker
But when I ran `yarn db:setup` I got the following error.
```
❯ yarn db:setup
yarn run v1.22.10
$ yarn db:migrate && yarn prisma generate
$ yarn -s prisma migrate up --experimental && yarn build:prisma
Environment variables loaded from prisma/.env
Prisma Schema loaded from prisma/schema.prisma
Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `postgresdocker` are not valid.
Please make sure to provide valid database credentials for the database server at `localhost`.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run …
```
=> fix: the prisma .env template was missing a colon between the username and password for the postgres url

.github/workflows/release.yml
This should fix the Release workflow when running on the main branch. Unfortunately I have no way to fully test until it is merged.
- use `github.event.workflow_run.head_branch` instead of `github.ref`
n/a
Fixes #120
=> ci: use the head_branch property of the workflow_run event 

packages/create-bison-app/template/graphql/modules/scalars.ts
This exposes the most commonly used ones.
Example usage: 
```ts
t.email('emailField')
t.phone('phoneField')
```
- adds email, phone, url scalars. 
n/a
Fixes #xxx
=> feat: expose common scalars from graphql-scalars

packages/create-bison-app/template/tests/helpers.ts, packages/create-bison-app/template/tests/jest.setup.js.ejs
The `migrate up` command no longer exists in our version of prisma. This changes to use the `migrate deploy` command.
After making this change and being able to run tests, I noticed the tests are failing. I started fixing them but this required a lot of changes. The main reason for this is because some of the generated files (GraphQL typings) are outdated. I'll get the tests passing in #154.
Fixes #157
=> Replace unsupported prisma command

packages/create-bison-app/template/README.md.ejs, packages/create-bison-app/template/components/LoginForm.tsx, packages/create-bison-app/template/components/SignupForm.tsx, packages/create-bison-app/template/package.json.ejs
This upgrade ours `react-hook-form` to the latest version.
- There were a couple breaking changes: https://github.com/react-hook-form/react-hook-form/blob/master/CHANGELOG.md#changes-16
-  `register` now has to spread as props
-  `errors` alias has been removed and now has to be accessed through `formState`
Fixes #159
=> chore: upgrade react-hook-form

packages/create-bison-app/template/graphql/modules/user.ts.ejs, packages/create-bison-app/template/jest.config.js, packages/create-bison-app/template/package.json.ejs, packages/create-bison-app/template/tests/requests/user/createUser.test.ts, packages/create-bison-app/template/tests/requests/user/signup.test.ts, packages/create-bison-app/template/tests/requests/user/users.test.ts, packages/create-bison-app/template/tests/unit/components/LoginForm.test.tsx, packages/create-bison-app/template/tests/unit/components/SignupForm.test.tsx
This PR works to resolve the failing tests after the initialization of an app. Two test suites skipped that are failing on next/link components.
- Add missing queries for User & Users that include authorization for all Users, resolves user tests
- Adding missing Inputs for User Create and Where clauses
- Skips the Login Form and Signup Form component tests as they have a failure on the dependent library that still needs to be resolved
Fixes #161
=> fix: broken tests after app init

.gitignore, CONTRIBUTING.md, packages/create-bison-app/CONTRIBUTING.md, packages/create-bison-app/index.js, packages/create-bison-app/package.json, packages/create-bison-app/scripts/createApp.js, packages/create-bison-app/scripts/createDevAppAndStartServer.js, packages/create-bison-app/tasks/copyFiles.js, packages/create-bison-app/utils/copyDirectoryWithTemplate.js, yarn.lock
This improves the developer experience and productivity to contribute to the bison template. It enables you to  make changes directly to files in `packages/create-bison-app/template/` and have it live reload a running bison app.
This adds a `yarn dev` script in `packages/create-bison-app` which will do the following:
1. Creates a new bison app in `packages/create-bison-app/dist/bison-dev-app`
-  If `packages/create-bison-app/dist/bison-dev-app` already exists, this step will be skipped
-  A `bison.json` file will also be created that contains all the variables for template rendering. This is needed later to watch and re-render EJS files. This file will **only** be created for this dev app and not other bison apps.
-  Symbolic links to node modules and generated files are created in …
=> feat: add dev server that will live reload on template changes

packages/create-bison-app/template/tests/helpers.ts
This fixes the command being run in `setupDB` to not fail in cypress tests when run multiple times on the same database.
- Replace `prisma deploy` with `prisma reset` so it will drop the database if it exists and then run migrations 
Fixes #170
=> fix: update setupDB command to not fail when run multiple times

packages/create-bison-app/template/_templates/graphql/new/graphql.ejs
Upgrades generated graphql nexus file with more CRUD examples and proper Input Types
GraphQL Nexus template was lacking, had bogus "SOMETHING" and User definitions. 
Now generates: 
- Base Module 
- Query `thing` w/ user logged in guard
- Query `list('thing')` w/ user logged in guard
- Mutation `createThing` w/ `isAdmin` guard
- Mutation `updateThing` w/ `IsAdmin` guard
- ThingWhereInput
- ThingWhereUniqueInput 
- ThingCreateInput
- ThingUpdateInput
- ThingOrderByInput
closes https://github.com/echobind/bisonapp/issues/173
=> feat(enhancement): Upgrades generated graphql nexus file with more CRUD examples

packages/create-bison-app/scripts/createDevAppAndStartServer.js
This fixes errors occurring when running `yarn dev --clean`:
- Update to not throw errors when removing directories if they don't exist
- Improves checking if symlinked files exist before removing. There were certain conditions where these were not being cleaned up.
- Updates to use `rm` instead of `rmdir` which is deprecated in node 16
=> fix: removing symlinked files and directories

packages/create-bison-app/scripts/createDevAppAndStartServer.js
The extension for the hygen templates was being removed when copied by the dev server:
- Updates to check if the changed file is a hygen template, if so do not call the `cleanTemplateDestPath` function which strips the file extension
=> fix: do not remove file extension from hygen templates when copied by dev server

packages/create-bison-app/index.js, packages/create-bison-app/scripts/createDevAppAndStartServer.js, packages/create-bison-app/utils/devAppVariables.js
The `scripts/*` files shouldn't be imported into other modules so this refactors getting and saving dev app variables into a utility file.
Fixes this error occurring when creating a new app:
=> fix: refactor scripts import in the create-bison-app script into utils file

.github/workflows/tests.yml
Currently, our tests workflow is not running on dependabot or public fork PRs so this adds the `pull_request` event as a trigger.
By default, first time contributors should need to get approval before the workflows run:
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository#configuring-required-approval-for-workflows-from-public-forks
=> ci: trigger on pull request event

README.md
Our CI docs were removed in a previous PR (https://github.com/echobind/bisonapp/pull/181) so this removes the broken links to it from the readme.
=> docs: remove broken links to CI docs

packages/create-bison-app/template/package.json.ejs
- This fixes the `yarn db:deploy` script which was running an outdated prisma command
=> fix: update db:deploy script to run correct prisma command

.github/workflows/release.yml
Runs "Release" workflow on node 16 so dependencies can be installed: https://github.com/echobind/bisonapp/runs/3678001603?check_suite_focus=true#step:7:14
=> ci: run release workflow on node 16

packages/create-bison-app/template/package.json.ejs
Temporary fix for CI cypress failures.
=> chore: pin down cypress version to 8.5

packages/create-bison-app/CONTRIBUTING.md, packages/create-bison-app/scripts/createDevAppAndStartServer.js
This is an improvement to the development workflow for the template. Before this change, you could only run `yarn dev` (from `packages/create-bison-app`) to run the template's `dev` script. This is still the default functionality.
Now in addition to that, `yarn dev` supports a new optional argument: `yarn dev [script]`
So from the `packages/create-bison-app` directory, you can run `yarn dev [script]` where `[script]` is the name of any script in `packages/create-bison-app/dist/bison-dev-app/package.json`. For example, you can run `yarn dev test` to run the "test" script in the bison app.
In the `packages/create-bison-app` directory, you can run `yarn dev test`, `yarn dev build:types`, or any script from the template's [package.json](https://github.com/echobind/bisonapp/blob/canary/packages …
=> feat: add ability to run any bison dev app script

packages/create-bison-app/template/components/Footer.tsx
External links are currently implemented with `<a>` tags in JSX. Chakra UI has a `Link` component which has the same functionality as `a`, while also making the links themeable through variants defined in the default or a custom theme via Chakra's theming API. See [this discussion](https://github.com/echobind/bisonapp/pull/235/commits/772a792b8aad287716ccf613fce8244071a75c91#r731948796) for context and an example. 
- Replaces use of anchor tags for external links with the `Link` component from Chakra UI
- Replace the use of `target="_blank"` and `rel="noopener noreferrer"` attributes on external links with the `isExternal` prop on the substituted `Link` components which provides the same functionality
=> feat: Make external links themeable with Chakra UI

packages/create-bison-app/template/package.json.ejs
- setup:dev now builds types before seeding
=> fix: generate initial types before db:setup

packages/create-bison-app/template/_.env.test.ejs
If you provide a database password during setup, the `DATABASE_URL` set in `.env.test` will not have a colon between the username and password. If no password is provided, it works fine.
=> fix: The DATABASE_URL set in .env.test doesn't include a colon between the username and password.

packages/create-bison-app/template/.vscode/launch.json
This PR adds several VSCode debugging configurations (`.vscode/launch.json`) to the default Bison template. Next.js now has [recommended configs](https://nextjs.org/docs/advanced-features/debugging#debugging-with-vs-code) for VSCode, which can be used to debug client and server code by setting breakpoints directly in the IDE. In addition to these debug configs, two more are included for debugging production builds and database seeding.
- Create a `.vscode/launch.json` file in the default Bison template and add debug configs recommended by Next.js team
- Add two additional configs for debugging production builds and database seeding in Bison
=> feat: add vscode debug configurations

README.md
This PR adds a link to download Postgres to the README to reduce ambiguity.
- README: link "Postgres" to their download page
=> Add Postgres download link to README

.github/workflows/tests.yml, packages/create-bison-app/template/package.json.ejs, packages/create-bison-app/utils/copyDirectoryWithTemplate.js
https://github.com/echobind/bisonapp/actions/runs/2386787858
- Refactors CI into multiple jobs. I did remove Node 18 from the node matrix, just because it seems excessive after introducing the OS matrix.
-  "create-app" Job
-  this runs on both Windows and Ubuntu 
- this will create a new bison app to ensure our CLI functionality works and uploads the app as an artifact
- "test" Job
-  this runs on Ubuntu only because a Postgres container is required and is only supported in Linux environments
- this downloads the app artifact from the previous job and will run lint, unit and end-to-end tests
- Fixes bugs in Windows copying template files when creating a new app
- Had to upgrade TypeScript and related dependencies to fix new errors with `ts-node-dev`. These would occur in new bison apps …
=> ci: add os matrix to run tests on windows
